# fly.toml app configuration file generated for detsy on 2023-05-06T22:07:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "detsy"
primary_region = "sea"

[build]
  image = "flyio/hellofly:latest"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
